name: Zig Tests

on:
  push:
    branches: [ "main", "feature", "codegen" ]
  pull_request:
    branches: [ "main", "feature", "codegen" ]
  release:
    types: [created, published]

jobs:
  test:
    name: Run Zig Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0 # Current zig version supported by the library
    
    - name: Run Tests
      run: zig build test --summary all